### ISSUE TITLE
'Create another?' link not present on limited sections

### ISSUE THREAD

**Issue by nathanhornby** [DeuxHuitHuit/limit_section_entries#13]
I've noticed that sections with a limit don't have the `Create another?` link in the header when an entry is created, even if the count is below the limit.

My assumption is that this is a limitation, that maybe the extension doesn't know the count when the entry is saved and so doesn't offer this link _just in case_, which is probably the best way to handle it - but thought I'd report it just in case it's a bug.

**Comment by nitriques** [comment]
Fixed! Thanks!
