### ISSUE TITLE
Coding style should be fixed

### ISSUE THREAD

**Issue by michael-e** [DeuxHuitHuit/limit_section_entries#18]
The coding style should be fixed. However, this usually makes `git blame` much harder (or even impossible), so I don't know what is the best time to do it.

If you want, I can send a PR (when all issues are closed?), just tell me.

**Comment by DavidOliver** [comment]
What is Symphony's chosen coding style/standard?

**Comment by nitriques** [comment]
@michael-e if you could send a PR based on top of the latest `dev` (which is d478b4e) I would then release the new version. All issues have been addressed. Thanks.

**Comment by nitriques** [comment]
Closed via 1796737 (#21), thanks @michael-e Sorry for the delay
