### ISSUE TITLE
Symphony 2.6 compatibility

### ISSUE THREAD

**Issue by michael-e** [DeuxHuitHuit/limit_section_entries#19]
There should be a new version which is declared to be compatible with Symphony 2.6. (I have not experienced issues with Symphony 2.6, apart from #14 and #16. But I suggest to also fix #18 before releasing a new version.)

**Comment by DavidOliver** [comment]
The basic functionality of this extension is also working for me in Sym 2.6. I haven't checked flash alerts/feedback notifications.

**Comment by nitriques** [comment]
Thanks! I've updated the meta file.
